# Generated by Django 4.2.5 on 2023-09-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('nebulosa', 'nebulosa'), ('estrela', 'estrela'), ('galáxia', 'galáxia'), ('planeta', 'planeta')], default='', max_length=100),
        ),
    ]
